# Generated by Django 5.0.6 on 2024-07-08 23:47

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionIva',
            fields=[
                ('id_condicion_iva', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Condición')),
                ('condicion_iva', models.CharField(max_length=100, verbose_name='Condición de IVA')),
            ],
            options={
                'db_table': 'condicion_iva',
            },
        ),
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Contacto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del mensaje')),
            ],
            options={
                'db_table': 'formulario_contacto',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID del Producto')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('vegano', models.BooleanField(default=False, verbose_name='Producto Vegano')),
                ('stock', models.PositiveBigIntegerField(default=0, verbose_name='Stock disponible')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('imagen', models.ImageField(default='imagenes_productos/default.jpg', upload_to='imagenes_productos/', verbose_name='Imagen del Producto')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('foto_cliente', models.ImageField(default='imagenes_clientes/default.jpg', upload_to='imagenes_clientes/', verbose_name='Foto del Cliente')),
                ('id_condicion_iva', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.condicioniva', verbose_name='ID de Condicion de IVA')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID de Pedido')),
                ('fecha_pedido', models.DateTimeField(verbose_name='Fecha Pedido')),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Despacho')),
                ('estado_pedido', models.CharField(max_length=50, verbose_name='Estado de Pedido')),
                ('costo_total', models.FloatField(verbose_name='Costo total del Pedido')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente', verbose_name='ID del Cliente')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID del Detalle del Pedido')),
                ('cantidad', models.PositiveBigIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.FloatField(verbose_name='Precio Unitario')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pedidos', verbose_name='ID del Pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productos', verbose_name='ID del Producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
