# Generated by Django 5.0.6 on 2024-07-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto_cliente',
            field=models.ImageField(default='static/img/imagenes_clientes/default.png', upload_to='static/img/imagenes_clientes/', verbose_name='Foto del Cliente'),
        ),
    ]
