# Generated by Django 5.0.6 on 2024-07-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_helado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto_cliente',
            field=models.ImageField(default='imagenes_clientes/default.png', upload_to='imagenes_clientes/', verbose_name='Foto del Cliente'),
        ),
    ]
